general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading = true
    fail_timeout = 1000
}

background {
    monitor =
    color = rgb(0, 0, 0)
    # all effects disabled for that raw TUI look
    blur_passes = 0
}

animations {
        enabled = false
    }

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = 0
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span foreground="white"></span>
    hide_input = false
    rounding = 0 # square corners
    check_color = rgb(255, 255, 255)
    fail_color = rgb(255, 0, 0) # slight hint of red only on failure
    fail_text = <i>FAIL</i>
    position = 0, 0
    halign = center
    valign = center
}
